version: '3.7'
services:

  database:
    image: postgres
    restart: always
    ports:
      - "6543:6543"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "MASTER_PASSWORD_REQUIRED=False"